### ISSUE TITLE
Unable to use wp_args within wp_sites in the config file

### ISSUE THREAD

**Issue by vesper1978** [tristanlatr/WPWatcher#40]
When I try and use wp_sites in the wpwatcher.conf file and set wp_args for a site, then running wpwatcher fails with the following:

```
 INFO - WPWatcher -  Automating WPscan to scan and report vulnerable Wordpress sites
Traceback (most recent call last):
  File "/usr/local/bin/wpwatcher", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/wpwatcher/cli.py", line 408, in main
    WPWatcherCLI()
  File "/usr/local/lib/python3.6/dist-packages/wpwatcher/cli.py", line 53, in __init__
    configuration = self.build_config_cli(args)
  File "/usr/local/lib/python3.6/dist-packages/wpwatcher/cli.py", line 343, in build_config_cli
    configuration, files = WPWatcherConfig(files=conf_files).build_config()
  File "/usr/local/lib/python3.6/dist-packages/wpwatcher/config.py", line 55, in __init__
    self.parser.read_file(fp)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/root/.wpwatcher/wpwatcher.old' [line 19]: option '{"url"' in section 'wpwatcher' already exists

```
Here's my conf with the actual URLs omitted:

```
[wpwatcher]
wp_sites=[
{"url":"url1.com","wpscan_args":["--ignore-main-redirect"]},
{"url":"url2.com"} ]
```
If I remove the wpscan_args protion, and only set the url, then it runs fine. However, I need to set different wpscan_args for each site I'll be scanning.

Any assistance with this would be appreciated.

**Comment by tristanlatr** [comment]
Hello,

I suspect this is due to your incorrect indentation. 

Try with:
```ini
[wpwatcher]
wp_sites=[
    {"url":"url1.com", "wpscan_args":["--ignore-main-redirect"]},
    {"url":"url2.com"} ]
```

Hope it helps !

:)

**Comment by vesper1978** [comment]
Thanks, that was exactly it!
